### ISSUE TITLE
Remember current page

### ISSUE THREAD

**Issue by emilaxelsson** [valderman/haste-deck#3]
It would be very convenient if reloading didn't take you back to the first page. Especially when working on large slide sets it becomes very tedious to have to step forward after each reload.

Slidy puts a `#(N)` in the URL to keep track of the slide number. This has the advantage that you can also reference specific pages.

**Comment by valderman** [comment]
Partially implemented in the latest commit; now you can start a presentation from a particular slide as well as continue from the same slide when reloading the page. Doesn't support changing slides through hyperlinks on the fly however; I want to think a bit more about how to do that with animations rather than just say "OK, hash changed, reload page".

**Comment by valderman** [comment]
Changing slides by setting the hash on the fly is now supported, animations and all. I also added support for left/right swipes on mobile devices while I was at it. Don't know how useful it is for presentations, but it's pretty cool.

**Comment by emilaxelsson** [comment]
Very nice!

However, I sometimes see slides switching places after reloading. For example:
- Load the [FP presentation](../../../emilaxelsson/fp-presentation-15/tree/master/slides)
- Press END key (moves slide #9)
- Reload
- Press left arrow (moves to slide #8 which now has the content of the first slide)

**Comment by emilaxelsson** [comment]
This was fixed a few days ago.
